### ISSUE TITLE
Doesn't seem to work in Windows 10

### ISSUE THREAD

**Issue by ryan0432** [yutent/scss-to-css#1]
Hello there, I found your scss to css in the marketplace. It looks amazing that it can translate scss to css automatically for you but it doesn't seem to work in Windows 10.
Should I install Ruby to make it work or anything else I have to do prior to the installation? Thanks for answering my question in advance.

**Comment by yutent** [comment]
Thanks for liking my work.
It seems that the `node-sass` can not work in `vscode`. Now I  use `sass.js` instead of it.
And now you can upgrade the extension in the marketplace.
