### ISSUE TITLE
请问.scsssrc文件是放在哪里呢？

### ISSUE THREAD

**Issue by qdchenyixuan** [yutent/scss-to-css#10]
请问.scsssrc文件是应该放在哪里呢？我跟着你的demo放在了跟.scss同一个文件夹里，不过没有生效。我是在vscode设置-拓展里配置的。
很喜欢你的这个插件和音乐播放器~这个插件对于写官网和活动页的有超大的优势，感觉去掘金这种社区发一些文章会有更多人star呢

**Comment by qdchenyixuan** [comment]
还有请问，. scsssrc我是放到和.scss同样的文件夹，貌似没有起作用，我看到您播放器那个项目里也没有这个配置文件，也不知道该怎么去Google找个问题。谢谢~

**Comment by yutent** [comment]
放在项目根目录就好。

**Comment by qdchenyixuan** [comment]
感谢
