### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jessengolab** [yutent/scss-to-css#11]
- Issue Type: `Performance`
- Extension Name: `scss-to-css`
- Extension Version: `2.1.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.32.3`

**Comment by yutent** [comment]
Hi,
You can upgrade `scss-to-css`  to 3.0.0
Before you upgrade you need  to install `node-sass` globally. (`npm i  -g node-sass`). And reload vscode's window after upgraded.
