### ISSUE TITLE
看了下您的commit,之前使用没问题，3.0版本在Mac上直接失效了

### ISSUE THREAD

**Issue by qdchenyixuan** [yutent/scss-to-css#12]
Mac版本10.13.6 
vscode最新版

之前使用无任何问题，今天忽然失效了。排除了自己语法错误等原因。
之前一个月一直在是用很少会出现问题，出问题也是重启一下就好了。

**Comment by qdchenyixuan** [comment]
刚刚非常慌张。。。
绝望之际看到了commit记录把全局sass依赖装上没有问题了。
希望您能建一个交流群，下次有这种变动可以通知一声。。多谢

**Comment by yutent** [comment]
更新日志上是有说的。 只是目前vscode的更新机制不太科学,  更新前没有弹出更新日志。
![image](https://user-images.githubusercontent.com/11972650/62527037-fe10bf80-b86c-11e9-936a-3651a9658b34.png)

**Comment by yutent** [comment]
纯js版的 `libsass`, 在vscode上有性能问题, 可能会导致vscode崩溃。而直接引用`node-sass`, 在vscode上有点问题, 加上要在不同平台上编译`node-sass`比较麻烦, 所以改为手动全局安装。
