### ISSUE TITLE
配置在哪里写?

### ISSUE THREAD

**Issue by XAihan** [yutent/scss-to-css#14]
配置在哪里写?

**Comment by yutent** [comment]
放在根目录就行。
![image](https://user-images.githubusercontent.com/11972650/70995314-38d40f80-210b-11ea-9591-6a4f453eff4a.png)


如果不需要单独为每个项目都配置一份独立的话, 直接在设置里修改全局配置也可以。

**Comment by XAihan** [comment]
了解,感谢大佬.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yutent"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 晚上8:24
收件人:&nbsp;"yutent/scss-to-css"<scss-to-css@noreply.github.com&gt;;
抄送:&nbsp;"席从波"<1172969610@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yutent/scss-to-css] 配置在哪里写? (#14)




放在根目录就行。
 
 
如果不需要单独为每个项目都配置一份独立的话, 直接在设置里修改全局配置也可以。
