### ISSUE TITLE
Windows路径分隔符未处理导致配置文件不生效

### ISSUE THREAD

**Issue by syfxlin** [yutent/scss-to-css#15]
在Node中需要对Windows的路径分隔符进行处理，否则会导致读取上的错误，造成配置文件不生效

![图片](https://user-images.githubusercontent.com/28844480/72961167-21afce00-3deb-11ea-924e-06a3c2816192.png)

在`if (fs.exists(configFile))`处没有处理Windows分隔符同时也是转义符的`\`，其他平台使用的是`/`来作为分隔符不会遇到该问题

**Comment by syfxlin** [comment]
emmm，vscode显示的是转义后的字符2333，问题出在`index.js`文件的第`153`行，将`path`改为`fsPath`即可。

**Comment by yutent** [comment]
本插件在 Linux 或者 Mac 下面测试通过。至于使用 Windows 并坚持玩新技术的同学，我坚信他们一定有着过人的、 甚至是不可告人的兼容性 bug 处理能力，所以这部分同学麻烦在安装过程无法继续时，自行兼容一下
