### ISSUE TITLE
编译完，顶部怎么出现了路径 

### ISSUE THREAD

**Issue by achengfu** [yutent/scss-to-css#16]
![image](https://user-images.githubusercontent.com/12210293/76200043-e4cd5880-622b-11ea-846c-37129828ee22.png)

**Comment by yutent** [comment]
你这是没编译成功的吧?你检查一下直接用命令行编译试试, 如果也有, 可能是你装的node-sass版本有bug了

**Comment by achengfu** [comment]
换用 Easy Sass 插件 可以了，可能你的这个插件确实对window~~！

**Comment by yutent** [comment]
> 换用 Easy Sass 插件 可以了，可能你的这个插件确实对window~~！

嗯嗯。
