### ISSUE TITLE
Output CSS to different folder

### ISSUE THREAD

**Issue by AlxTheRed** [yutent/scss-to-css#2]
Love how easy this plugin is to setup and start compiling Scss without having to mess around with Node, etc. Is it possible to output the CSS to a different folder?

For example, I'm working with a WordPress theme where the Sass is in a 'sass' folder, but the CSS file need to be in the theme's root folder. 

Is there a way to set that up in a config?

**Comment by yutent** [comment]
These features will be added next version.

**Comment by yutent** [comment]
Now versin 2.0.0 was published.
