### ISSUE TITLE
不知道是否能增加错误提示？

### ISSUE THREAD

**Issue by ChiefWang93** [yutent/scss-to-css#22]
@include shadowLarge;  
像这种引用失效，没有提示，今天找了一天问题，才发现误删了。
如果可以提示在哪个位置出错就好了。

**Comment by yutent** [comment]
想在输入的时候实时提示的话, 就没办法了, 只能你自己用 eslint等工具了。
但是编译的时候, 是有错误输出的,  你打开调试面板, 能看到的

![image](https://user-images.githubusercontent.com/11972650/125610669-1c9f61b3-f54e-436f-a542-8f6dbc34a988.png)
