### ISSUE TITLE
Error: Can't find stylesheet to import

### ISSUE THREAD

**Issue by netparty-adv** [yutent/scss-to-css#23]
Good day,
Latest version, 3.1.0, throws an exception "**Error: Can't find stylesheet to import.**"
Previous version was ok, and all existing scss files worked like expected
![Screenshot 2021-07-23 154003](https://user-images.githubusercontent.com/25440735/126782859-7755b742-5852-477d-87d8-b4c19b447702.png)

**Comment by gn131131** [comment]
I'v had the same issue，previous version was ok, and i have installed sass instead

**Comment by gn131131** [comment]
> I'v had the same issue，previous version was ok, and i have installed sass instead

use sass --watch input.scss output.css in terminal
did work，the plugin's problem maybe

**Comment by yutent** [comment]
upgrade to v3.1.1 will work.
