### ISSUE TITLE
Cannot include SourceMappingURL

### ISSUE THREAD

**Issue by math-GH** [yutent/scss-to-css#29]
I like your extension very much. It helps me a lot to convert scss file to css.

Right now I am working in a project, where the css file has a `sourceMappingURL` information as a single line.

`/*# sourceMappingURL=mycssfile.css.map */`

I do not find a way to include it in the final css file.
It does not work to include this comment line into the scss. It will not converted into the css file.

Any ideas? Or is a feature missing here?

**Comment by yutent** [comment]
sorry, but I have no plan for the feature.
