### ISSUE TITLE
SCSS highlight Container Queries as error

### ISSUE THREAD

**Issue by XCanG** [yutent/scss-to-css#31]
There is new [Container Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries) that this addon has no support.

Additionally I would like to request option to disable error warnings in the settings, so that if some new CSS rules will be added, I can suppress error.

**Comment by yutent** [comment]
![image](https://user-images.githubusercontent.com/11972650/217134258-19870729-d300-4fdf-a043-ed304ab37e11.png)

**Comment by XCanG** [comment]
Oh, I might mistake then, since I didn't have any other addons related to SCSS. Sorry to bother you.

**Comment by yutent** [comment]
> Oh, I might mistake then, since I didn't have any other addons related to SCSS. Sorry to bother you.

It's the build-in feature. you should create an issue to vscode.
