### ISSUE TITLE
Feature - customise extension

### ISSUE THREAD

**Issue by 350d** [yutent/scss-to-css#32]
Please add an option to customise compressed file suffix/extension, like `.min.css` or `.css`.

**Comment by yutent** [comment]
This is a deprecated feature with no plans to bring it back

**Comment by 350d** [comment]
I don't get it, sorry, but why this standard basic feature for all SCSS processors deprecated here?

**Comment by robwynnejones** [comment]
Also needed this, would be so useful as I can't get this to now fit into our current setup.
