### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Truonghuu478** [yutent/scss-to-css#4]
- Issue Type: `Performance`
- Extension Name: `scss-to-css`
- Extension Version: `2.0.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\truong oppa\yutent.scss-to-css-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by yutent** [comment]
Upload that file here, please.
