### ISSUE TITLE
自从装了你这个插件后，vscode就崩了，一直报宿主崩溃

### ISSUE THREAD

**Issue by Leeesin** [yutent/scss-to-css#8]
卸载插件，问题解决了，希望作者修复下这个bug

**Comment by yutent** [comment]
好像是那个 新版的sass插件的搞的鬼, 我这里崩溃过好几次。 晚点我降回旧版本看看了。
唉, 要不是要兼容windows10那辣鸡, 不然哪有那么多破事呀

**Comment by Leeesin** [comment]
辛苦啦

**Comment by yutent** [comment]
目前更新到最新版的libsass, 貌似没崩溃了, 你再观察观察看。

**Comment by Leeesin** [comment]
好的，辛苦了




------------------ 原始邮件 ------------------
发件人: "yutent"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 下午4:27
收件人: "yutent/scss-to-css"<scss-to-css@noreply.github.com>; 
抄送: "954551222"<954551222@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yutent/scss-to-css] 自从装了你这个插件后，vscode就崩了，一直报宿主崩溃 (#8)




目前更新到最新版的libsass, 貌似没崩溃了, 你再观察观察看。

**Comment by yutent** [comment]
不客气。 最近这2个月比较忙, 本该早就处理的问题现在才有空。
