### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by obear997** [yutent/scss-to-css#9]
你好，我按照了插件，可是保存scss的时候无法编译

**Comment by yutent** [comment]
你好, 能提供一下你的系统环境信息么, 包括 系统版本、vscode版本等

**Comment by obear997** [comment]
我的系统是win10 专业版 64为（17134），vs code是1.34.0

**Comment by yutent** [comment]
我这无法重现你说的问题呢

**Comment by obear997** [comment]
我简单跟你描述一下情况： 我在vs code拓展里面搜索到'scss-to-css'，安装，正常情况下不需要配置setting,json，只需编辑scss然后保存就会自动编译的对吧？ 但是我这边没有任何反应，状态条没有出现提示，任务里面也没有提示，也没有输出文件

**Comment by yutent** [comment]
我在虚拟机里测试, 并没有重现你所说的问题。也是0配置。
默认是不需要配置任何参数就可以简单的编译scss的。 
但是有个前提, 文件后缀名必须是`.scss`, 不支持`.sass`或其他。
